[package]
name = "test_rust_decimal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.24"
rust_decimal_macros = "1.24"
boolinator = "2.4.0"